# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.0.0-beta.8

import winsdk.system

_ns_module = winsdk.system._import_ns_module("Windows.System.Implementation.FileExplorer")

try:
    import winsdk.windows.foundation
except ImportError:
    pass

try:
    import winsdk.windows.web.http
except ImportError:
    pass


SysStorageProviderEventReceivedEventArgs = _ns_module.SysStorageProviderEventReceivedEventArgs
ISysStorageProviderEventSource = _ns_module.ISysStorageProviderEventSource
ISysStorageProviderHandlerFactory = _ns_module.ISysStorageProviderHandlerFactory
ISysStorageProviderHttpRequestProvider = _ns_module.ISysStorageProviderHttpRequestProvider
