# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.0.0-beta.2

import winsdk

_ns_module = winsdk._import_ns_module("Windows.System.Threading.Core")

try:
    import winsdk.windows.foundation
except Exception:
    pass

try:
    import winsdk.windows.system.threading
except Exception:
    pass

PreallocatedWorkItem = _ns_module.PreallocatedWorkItem
SignalNotifier = _ns_module.SignalNotifier
