// WARNING: Please don't edit this file. It was generated by Python/WinRT v1.0.0-beta.1

#pragma once

#include "pybase.h"

#if __has_include("py.Windows.Foundation.h")
#include "py.Windows.Foundation.h"
#endif

#if __has_include("py.Windows.Foundation.Collections.h")
#include "py.Windows.Foundation.Collections.h"
#endif

#include <winrt/Windows.System.Update.h>

namespace py::proj::Windows::System::Update
{}

namespace py::impl::Windows::System::Update
{}

namespace py::wrapper::Windows::System::Update
{
    using SystemUpdateItem = py::winrt_wrapper<winrt::Windows::System::Update::SystemUpdateItem>;
    using SystemUpdateLastErrorInfo = py::winrt_wrapper<winrt::Windows::System::Update::SystemUpdateLastErrorInfo>;
    using SystemUpdateManager = py::winrt_wrapper<winrt::Windows::System::Update::SystemUpdateManager>;
}

namespace py
{
    template<>
    struct winrt_type<winrt::Windows::System::Update::SystemUpdateItem>
    {
        static PyTypeObject* python_type;
        static PyTypeObject* get_python_type() { return python_type; }
    };

    template<>
    struct winrt_type<winrt::Windows::System::Update::SystemUpdateLastErrorInfo>
    {
        static PyTypeObject* python_type;
        static PyTypeObject* get_python_type() { return python_type; }
    };

    template<>
    struct winrt_type<winrt::Windows::System::Update::SystemUpdateManager>
    {
        static PyTypeObject* python_type;
        static PyTypeObject* get_python_type() { return python_type; }
    };

}
