// WARNING: Please don't edit this file. It was generated by Python/WinRT v1.0.0-beta.5

#pragma once

#include "pybase.h"

#if __has_include("py.Windows.Foundation.h")
#include "py.Windows.Foundation.h"
#endif

#if __has_include("py.Windows.Foundation.Collections.h")
#include "py.Windows.Foundation.Collections.h"
#endif

#include <winrt/Windows.Security.Authentication.Web.h>

namespace py::proj::Windows::Security::Authentication::Web
{}

namespace py::impl::Windows::Security::Authentication::Web
{}

namespace py::wrapper::Windows::Security::Authentication::Web
{
    using WebAuthenticationBroker = py::winrt_wrapper<winrt::Windows::Security::Authentication::Web::WebAuthenticationBroker>;
    using WebAuthenticationResult = py::winrt_wrapper<winrt::Windows::Security::Authentication::Web::WebAuthenticationResult>;
}

namespace py
{

    template<>
    struct py_type<winrt::Windows::Security::Authentication::Web::TokenBindingKeyType>
    {
        static PyObject* get_python_type() noexcept;
    };

    template<>
    struct py_type<winrt::Windows::Security::Authentication::Web::WebAuthenticationOptions>
    {
        static PyObject* get_python_type() noexcept;
    };

    template<>
    struct py_type<winrt::Windows::Security::Authentication::Web::WebAuthenticationStatus>
    {
        static PyObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Security::Authentication::Web::WebAuthenticationBroker>
    {
        static PyTypeObject* get_python_type() noexcept;
    };

    template<>
    struct winrt_type<winrt::Windows::Security::Authentication::Web::WebAuthenticationResult>
    {
        static PyTypeObject* get_python_type() noexcept;
    };
}
