# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.0.0-beta.1

import enum
import sys
import types
import typing
import uuid

import winsdk._winrt as _winrt

try:
    import winsdk.windows.foundation
except Exception:
    pass

try:
    import winsdk.windows.foundation.collections
except Exception:
    pass

try:
    import winsdk.windows.networking.sockets
except Exception:
    pass

try:
    import winsdk.windows.security.credentials
except Exception:
    pass

try:
    import winsdk.windows.security.cryptography.certificates
except Exception:
    pass

try:
    import winsdk.windows.system
except Exception:
    pass

try:
    import winsdk.windows.web.http
except Exception:
    pass

class HttpCacheReadBehavior(enum.IntEnum):
    DEFAULT = 0
    MOST_RECENT = 1
    ONLY_FROM_CACHE = 2
    NO_CACHE = 3

class HttpCacheWriteBehavior(enum.IntEnum):
    DEFAULT = 0
    NO_CACHE = 1

class HttpCookieUsageBehavior(enum.IntEnum):
    DEFAULT = 0
    NO_COOKIES = 1

class HttpBaseProtocolFilter(IHttpFilter, winsdk.windows.foundation.IClosable, _winrt.Object):
    ...
    use_proxy: _winrt.Boolean
    server_credential: winsdk.windows.security.credentials.PasswordCredential
    proxy_credential: winsdk.windows.security.credentials.PasswordCredential
    max_connections_per_server: _winrt.UInt32
    client_certificate: winsdk.windows.security.cryptography.certificates.Certificate
    automatic_decompression: _winrt.Boolean
    allow_u_i: _winrt.Boolean
    allow_auto_redirect: _winrt.Boolean
    cache_control: HttpCacheControl
    cookie_manager: winsdk.windows.web.http.HttpCookieManager
    ignorable_server_certificate_errors: winsdk.windows.foundation.collections.IVector[winsdk.windows.security.cryptography.certificates.ChainValidationResult]
    max_version: winsdk.windows.web.http.HttpVersion
    cookie_usage_behavior: HttpCookieUsageBehavior
    user: winsdk.windows.system.User
    def __init__(self, ) -> None:
        ...
    def clear_authentication_cache() -> None:
        ...
    def close() -> None:
        ...
    def create_for_user(user: winsdk.windows.system.User) -> HttpBaseProtocolFilter:
        ...
    def send_request_async(request: winsdk.windows.web.http.HttpRequestMessage) -> winsdk.windows.foundation.IAsyncOperationWithProgress[winsdk.windows.web.http.HttpResponseMessage, winsdk.windows.web.http.HttpProgress]:
        ...
    def add_server_custom_validation_requested(handler: winsdk.windows.foundation.TypedEventHandler[HttpBaseProtocolFilter, HttpServerCustomValidationRequestedEventArgs]) -> winsdk.windows.foundation.EventRegistrationToken:
        ...
    def remove_server_custom_validation_requested(token: winsdk.windows.foundation.EventRegistrationToken) -> None:
        ...

class HttpCacheControl(_winrt.Object):
    ...
    write_behavior: HttpCacheWriteBehavior
    read_behavior: HttpCacheReadBehavior

class HttpServerCustomValidationRequestedEventArgs(_winrt.Object):
    ...
    request_message: winsdk.windows.web.http.HttpRequestMessage
    server_certificate: winsdk.windows.security.cryptography.certificates.Certificate
    server_certificate_error_severity: winsdk.windows.networking.sockets.SocketSslErrorSeverity
    server_certificate_errors: winsdk.windows.foundation.collections.IVectorView[winsdk.windows.security.cryptography.certificates.ChainValidationResult]
    server_intermediate_certificates: winsdk.windows.foundation.collections.IVectorView[winsdk.windows.security.cryptography.certificates.Certificate]
    def get_deferral() -> winsdk.windows.foundation.Deferral:
        ...
    def reject() -> None:
        ...

class IHttpFilter(winsdk.windows.foundation.IClosable, _winrt.Object):
    ...
    def send_request_async(request: winsdk.windows.web.http.HttpRequestMessage) -> winsdk.windows.foundation.IAsyncOperationWithProgress[winsdk.windows.web.http.HttpResponseMessage, winsdk.windows.web.http.HttpProgress]:
        ...
    def close() -> None:
        ...

