# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.0.0-beta.5

import sys
import types
import typing
import uuid

import winsdk._winrt as _winrt

Self = typing.TypeVar('Self')

class IGraphicsEffect(_winrt.Object):
    name: str
    @staticmethod
    def _from(obj: _winrt.Object) -> IGraphicsEffect: ...

class IGraphicsEffectSource(_winrt.Object):
    @staticmethod
    def _from(obj: _winrt.Object) -> IGraphicsEffectSource: ...

